version: '3.8'

services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: srealitydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 87654312
    ports:
      - "5432:5432"

  code:
    build:
      context: ./code
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:87654312@db:5432/postgres
    ports:
      - "8080:8080"